language: "perl"

perl:
  - "5.14"

env:

before_install:
    - sudo apt-get -y update
    - sudo apt-get -y install unzip
    - sudo apt-get -y install sendmail
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-external.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-analysis.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-killlist.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip


install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - mkdir modules/Bio/EnsEMBL/Pipeline/Config/GeneBuild
    - echo "1;" > modules/Bio/EnsEMBL/Pipeline/Config/GeneBuild/Databases.pm
    - mkdir modules/Bio/EnsEMBL/Pipeline/Config/Protein_Annotation
    - echo "1;" > modules/Bio/EnsEMBL/Pipeline/Config/Protein_Annotation/General.pm
    - echo "1;" > modules/Bio/EnsEMBL/Pipeline/Tools/TranscriptUtils.pm
 
script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always

